In [1]:
print("Hello World")

Hello World


### NumPy

In [2]:
import numpy as np

**Creating numpy arrays**

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3], [4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(mylist)

### 2-dimensional array/matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mymatrix.shape

(3, 3)

**There are different ways to create arrays**

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

### It is a floating point number

array([0., 0., 0., 0., 0.])

In [15]:
type(0.)

float

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [19]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [20]:
### The above operations (+,-,/,*) does not work with regular lists

[1,1,1,1]*5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [21]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [22]:
len(np.linspace(0, 10, 12))

12

In [23]:
### Creating an indentity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Creating random numbers**

In [24]:
### Uniform random number

np.random.rand(1)

array([0.7085495])

In [25]:
np.random.rand(2)

array([0.25600042, 0.34326493])

In [26]:
np.random.rand(3,3)

array([[0.60129644, 0.8727674 , 0.46079908],
       [0.55432073, 0.60927319, 0.1655447 ],
       [0.27599667, 0.18811342, 0.25943835]])

In [27]:
### Standard normal random number

np.random.randn(1)

array([1.21846167])

In [28]:
### Normal random numbers

np.random.normal(loc=10, scale=3, size = 5)

array([ 8.47572457,  4.5321723 , 14.41160607,  9.49140879, 11.15452437])

In [29]:
### Random number between two numbers

np.random.randint(1,100)

69

In [30]:
np.random.randint(1,100, 2)

array([28, 26])

In [31]:
### Set seed to fix random numbers

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
arr.reshape(5,5)

### Dimentions should match the number of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
### Maximum value

ranarr.max()

39

In [36]:
ranarr.min()

2

In [37]:
### find index location of maximum value

ranarr.argmax()

7

In [38]:
ranarr.argmin()

9

In [39]:
ranarr.dtype

dtype('int32')

**Index selection**

In [40]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[7]

7

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[:3]

array([0, 1, 2])

In [44]:
arr[0:3]

array([0, 1, 2])

In [45]:
new_arr = arr + 100
new_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
### Note: It has affected original array. We can avaoid this propoerly copying original array

In [50]:
arr_copy = arr.copy()
arr_copy[:] = 10000
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
### Index 2-dimensional array/matrix

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
arr_2d.shape

(3, 3)

In [54]:
### Pick index 1 row

arr_2d[1]

array([20, 25, 30])

In [55]:
arr_2d[1][2]

30

In [56]:
arr_2d[2,2]

45

In [57]:
### More than two numbers:

arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
### Conditional selection

In [60]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
### In a single step:

arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

**Numpy operations**

In [65]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [67]:
(arr + 100)/20

array([5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 , 5.45])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
### Above operations are perfromed element by element

In [70]:
1/arr

C:\Users\sulal\AppData\Local\Temp\ipykernel_14428\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [71]:
### Note: Devide by zero gives and warning and placeholder with "inf"

In [72]:
### Number of built in functions are there:

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.log(arr)

C:\Users\sulal\AppData\Local\Temp\ipykernel_14428\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [75]:
arr.sum()

45

In [76]:
arr.mean()

4.5

In [77]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
arr_2d.shape

(3, 4)

In [79]:
arr_2d.sum()

78

In [80]:
### Note: In practice, we may want to sum up all the values in a rwo/column

In [81]:
arr_2d.sum(axis = 0) ### Sum across the rows

array([15, 18, 21, 24])

In [82]:
arr_2d.sum(axis = 1) ### Sum across the columns

array([10, 26, 42])