### PyTorch Basics

Here will cover PyTorch tensors with some basics, how to create tensors, their operations, along with some exercises.

What is a tensor? A tensor is often thought of as a generalized matrix (1-D, 2-D, 3-D, ..., N-D tensors). It is a more generalized term.

Commaly used names:
- scalar
- 1-D == vector
- 2-D == Matrix
- 3-D and above == tensor

We use these tensors to arrange our data. When working with image data, it will be easiest to work with it as 3D tensors (view as different layers).

#### Tensor Basics

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.5.1'

**Converting normal numpy array to pytorch tensor**

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [7]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
### Alternative approach (more generalized approach):

torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [12]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [14]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
### Note that both "from_numpy" and "as_tensor" retain relationship betwwen numpy array and tensor object.

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [19]:
x

### First value of x is now 99. In some cases we do not want this.

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [20]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [23]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

Note that `torch.tensor` allocates a separate memory location, and thus it will not update the tensor object when we make changes to the numpy array.

**Creating a tesnor from scratch in PyTorch**

In [26]:
### Before moving forward, let's quickly check the difference between "tensor" and "Tensor".
### The main difference is data type.

new_arr = np.array([1,2,3])
new_arr

array([1, 2, 3])

In [27]:
new_arr.dtype

dtype('int32')

In [28]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [30]:
my_Tensor = torch.Tensor(new_arr)
my_Tensor.dtype

torch.float32

In [31]:
### When dealing neural networks, we may want to create empty tensors (allocate memeory/place holder), later filled with findings.

In [32]:
### Retain a block of memory/a placeholder

torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [33]:
### Alternatively:

torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
### We can also specify the data type.

torch.zeros(4,3, dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [37]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [38]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [39]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [40]:
### In some cases we may need more precision. That is instead of int32, int64. Or reduce the accuracy.

In [41]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [42]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [44]:
### In soma cases we may also need some random numbers (starting weights of NN could be some random values).

In [45]:
### Random sample from uniform distribution:

torch.rand(4,3)

tensor([[0.3141, 0.6627, 0.7470],
        [0.3422, 0.2107, 0.7213],
        [0.4754, 0.3403, 0.5044],
        [0.4888, 0.5116, 0.9016]])

In [46]:
### Random sample from standard normal distribution:

torch.randn(4,3)

tensor([[ 0.4967,  0.5669,  0.9015],
        [-0.9667, -1.0725, -1.0427],
        [ 0.1934, -1.8628,  1.5445],
        [ 0.2564,  0.9776,  2.0044]])

In [47]:
torch.randint(low = 0, high = 10, size = (5,5))

### Note: "high" is exluded.

tensor([[3, 0, 5, 8, 8],
        [8, 5, 4, 7, 5],
        [2, 6, 9, 2, 6],
        [4, 6, 0, 9, 0],
        [8, 1, 1, 6, 9]])

In [48]:
### Let's say we want to pass information about the size of a tensor.
### Example: next layer in my NN has the same dimensions as the incoming tensor.

x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.rand_like(x)

tensor([[0.3935, 0.3910, 0.5333, 0.4242, 0.6919],
        [0.2399, 0.3826, 0.4637, 0.0821, 0.7148]])

In [50]:
### If we need only integers (we still need to specify low and high for the range)

torch.randint_like(x, low = 0, high = 10)

tensor([[4., 9., 5., 9., 8.],
        [9., 6., 7., 2., 9.]])

In [51]:
### Set the seed for reproducibility:

torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [52]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [53]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [54]:
### Note: set seed in the same cell.

**Tensor Operations**

In [55]:
### Create a 2D tensor

x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [56]:
### Pick a single value from x

x[1,1]

tensor(3)

In [57]:
### Note: it returns as a tensor object

In [58]:
type(x[1,1])

torch.Tensor

In [59]:
### SLicers

x[:,1]

tensor([1, 3, 5])

In [60]:
### Note: Even though we are trying to get column 1, it does not retain as a column (we expect a 3 by 1 vector)/vertical vector.
### Instead, we see a 1 by 3 vector.

In [61]:
### One way to solve this:

x[:,1:]

tensor([[1],
        [3],
        [5]])

In [62]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
### There is a way to change how it can viewed without changing the original tensor.

In [64]:
### We can simply use "view":

x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [65]:
x

### Note: Shape of the "x" has not changed.

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
### Or we can use "reshape":

x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
### If you want to make the reshape permanent:

x = x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [69]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x.shape

torch.Size([10])

In [71]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [72]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [73]:
x[0] = 9999
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [74]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [75]:
### This means "view" is reflecting most recent data.

In [76]:
### "view" can also infer the correct size.
### Example:

In [77]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x.shape

torch.Size([10])

In [79]:
### By typing "-1", Pytorch is going to infer what would be the second dimension.
### This helps a lot when dealing with high-dimensional tensors.

x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [80]:
### Basic arithmetics with tensors:

In [81]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [82]:
b = torch.tensor([4.,5.,6.])
b

tensor([4., 5., 6.])

In [83]:
a.dtype

torch.float32

In [84]:
b.dtype

torch.float32

In [85]:
### Element by element operations:

a + b

### Note: Using "+" is similar to using the underlying function "add".

tensor([5., 7., 9.])

In [86]:
torch.add(a,b)

tensor([5., 7., 9.])

In [87]:
### Let's assume we want to do: a = a + b
### We can perform this with "add". There is also a function "add_" (underscore method)
### Let's see how they are different (This works for other operations such as multiplication)

a.mul(b)

tensor([ 4., 10., 18.])

In [88]:
a

### a is unchanged

tensor([1., 2., 3.])

In [89]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [90]:
a

### a is replaced now.

tensor([ 4., 10., 18.])