### PyTorch Basics

Here will cover PyTorch tensors with some basics, how to create tensors, their operations, along with some exercises.

What is a tensor? A tensor is often thought of as a generalized matrix (1-D, 2-D, 3-D, ..., N-D tensors). It is a more generalized term.

Commaly used names:
- scalar
- 1-D == vector
- 2-D == Matrix
- 3-D and above == tensor

We use these tensors to arrange our data. When working with image data, it will be easiest to work with it as 3D tensors (view as different layers).

#### Tensor Basics

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.5.1'

**Converting normal numpy array to pytorch tensor**

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [7]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
### Alternative approach (more generalized approach):

torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [12]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [14]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
### Note that both "from_numpy" and "as_tensor" retain relationship betwwen numpy array and tensor object.

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [19]:
x

### First value of x is now 99. In some cases we do not want this.

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [20]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [23]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

Note that `torch.tensor` allocates a separate memory location, and thus it will not update the tensor object when we make changes to the numpy array.

**Creating a tesnor from scratch in PyTorch**

In [26]:
### Before moving forward, let's quickly check the difference between "tensor" and "Tensor".
### The main difference is data type.

new_arr = np.array([1,2,3])
new_arr

array([1, 2, 3])

In [27]:
new_arr.dtype

dtype('int32')

In [28]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [30]:
my_Tensor = torch.Tensor(new_arr)
my_Tensor.dtype

torch.float32

In [31]:
### When dealing neural networks, we may want to create empty tensors (allocate memeory/place holder), later filled with findings.

In [32]:
### Retain a block of memory/a placeholder

torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [33]:
### Alternatively:

torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
### We can also specify the data type.

torch.zeros(4,3, dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [37]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [38]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [39]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [40]:
### In some cases we may need more precision. That is instead of int32, int64. Or reduce the accuracy.

In [41]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [42]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [44]:
### In soma cases we may also need some random numbers (starting weights of NN could be some random values).

In [45]:
### Random sample from uniform distribution:

torch.rand(4,3)

tensor([[0.3207, 0.3828, 0.1122],
        [0.5661, 0.0881, 0.1974],
        [0.1362, 0.3336, 0.8674],
        [0.6246, 0.3978, 0.5360]])

In [46]:
### Random sample from standard normal distribution:

torch.randn(4,3)

tensor([[ 1.0378, -0.1910, -0.6296],
        [-0.3406,  0.5780, -0.0635],
        [ 0.4043,  0.1337, -1.1292],
        [-0.6395,  0.3604,  0.0370]])

In [47]:
torch.randint(low = 0, high = 10, size = (5,5))

### Note: "high" is exluded.

tensor([[2, 0, 5, 0, 1],
        [0, 4, 4, 3, 5],
        [6, 3, 1, 9, 3],
        [5, 7, 5, 3, 4],
        [1, 4, 9, 2, 3]])

In [48]:
### Let's say we want to pass information about the size of a tensor.
### Example: next layer in my NN has the same dimensions as the incoming tensor.

x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.rand_like(x)

tensor([[0.3110, 0.0914, 0.4762, 0.6401, 0.1557],
        [0.8043, 0.8500, 0.5445, 0.7379, 0.4229]])

In [50]:
### If we need only integers (we still need to specify low and high for the range)

torch.randint_like(x, low = 0, high = 10)

tensor([[7., 5., 8., 4., 5.],
        [1., 8., 4., 5., 8.]])

In [51]:
### Set the seed for reproducibility:

torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [52]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [53]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [54]:
### Note: set seed in the same cell.