In [1]:
print("Hello World")

Hello World


### NumPy

In [1]:
import numpy as np

**Creating numpy arrays**

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [7]:
arr = np.array(mylist)
arr

array([1, 2, 3])

In [9]:
mylist = [[1,2,3], [4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(mylist)

### 2-dimensional array/matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mymatrix.shape

(3, 3)

**There are different ways to create arrays**

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5)

### It is a floating point number

array([0., 0., 0., 0., 0.])

In [18]:
type(0.)

float

In [19]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [25]:
### The above operations (+,-,/,*) does not work with regular lists

[1,1,1,1]*5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [29]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [30]:
len(np.linspace(0, 10, 12))

12

In [31]:
### Creating an indentity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Creating random numbers**

In [32]:
### Uniform random number

np.random.rand(1)

array([0.96426595])

In [33]:
np.random.rand(2)

array([0.01178183, 0.08045203])

In [34]:
np.random.rand(3,3)

array([[0.31838347, 0.54904153, 0.39815842],
       [0.0395464 , 0.81271663, 0.97740348],
       [0.52260181, 0.20252932, 0.92995927]])

In [35]:
### Standard normal random number

np.random.randn(1)

array([-0.53067109])

In [41]:
### Normal random numbers

np.random.normal(loc=10, scale=3, size = 5)

array([ 9.67674112, 10.88477672,  9.04252938,  8.67024972, 10.75873815])

In [43]:
### Random number between two numbers

np.random.randint(1,100)

54

In [44]:
np.random.randint(1,100, 2)

array([60, 27])

In [47]:
### Set seed to fix random numbers

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [48]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [51]:
arr.reshape(5,5)

### Dimentions should match the number of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
### Maximum value

ranarr.max()

43

In [53]:
ranarr.min()

1

In [56]:
### find index location of maximum value

ranarr.argmax()

3

In [57]:
ranarr.argmin()

1

In [59]:
ranarr.dtype

dtype('int32')