### PyTorch Basics

Here will cover PyTorch tensors with some basics, how to create tensors, their operations, along with some exercises.

What is a tensor? A tensor is often thought of as a generalized matrix (1-D, 2-D, 3-D, ..., N-D tensors). It is a more generalized term.

Commaly used names:
- scalar
- 1-D == vector
- 2-D == Matrix
- 3-D and above == tensor

We use these tensors to arrange our data. When working with image data, it will be easiest to work with it as 3D tensors (view as different layers).

#### Tensor Basics

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.5.1'

**Converting normal numpy array to pytorch tensor**

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [7]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
### Alternative approach (more generalized approach):

torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [12]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [14]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
### Note that both "from_numpy" and "as_tensor" retain relationship betwwen numpy array and tensor object.

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [19]:
x

### First value of x is now 99. In some cases we do not want this.

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [20]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [23]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

Note that `torch.tensor` allocates a separate memory location, and thus it will not update the tensor object when we make changes to the numpy array.

**Creating a tesnor from scratch in PyTorch**

In [29]:
### Before moving forward, let's quickly check the difference between "torch" and "Torch".
### The main difference is data type.

new_arr = np.array([1,2,3])
new_arr

array([1, 2, 3])